name: Sync Commits from Upstream

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  sync:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/centpays-tech/NodeBackend.git
          git fetch upstream
          git checkout main  # Adjust this to match your main branch
          git merge upstream/main --no-edit  # Adjust branch names if needed
          git push origin main  # Adjust branch names if needed
